# Generated by Django 3.2.4 on 2021-07-31 10:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userincome', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnserIncome',
            new_name='UserIncome',
        ),
    ]
